disabled_rules:
  - trailing_whitespace
  - unused_optional_binding
  - todo
  - FIXME

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - sorted_imports
  - prefer_self_type
  - closure_spacing
  - collection_alignment

included:
  - MiniChat
  - MiniChatTests

excluded:
  - MiniChat/Assets.xcassets
  - MiniChat/Preview\ Content
  - Pods

line_length:
  warning: 140
  error: 200

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - to
    - x
    - y
    - i
    - j

function_body_length:
  warning: 60
  error: 120

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000
